#!/bin/bash
#
#
#  _ _    _             _ 
# (_) | _(_) __ _  __ _(_)
# | | |/ / |/ _` |/ _` | |
# | |   <| | (_| | (_| | |
# |_|_|\_\_|\__, |\__,_|_|
#           |___/         
# 
# www.github.com/yedhink
#
# a system info scripted with love

name=$USER
distro="arch linux"
kernel=`uname -r`
wm=`wmctrl -m | grep -i name | awk '{print $2}'`
pkgs=`pacman -Qqs | wc -l`
she=`echo $SHELL | cut -d / -f 3` 
dt=`date | awk '{print $1" "$2" "$3}'`
up=`uptime -p`

red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
bprp="\e[35;1m"
rst="\e[0m"

echo -e "   ${red}                                 ____                 "  
echo -e "   ${red}                               d88P..b                "
echo -e "   ${red}                              d88P..88b               "
echo -e "   ${red}8888888888888888F.           |888    .88b             "
echo -e "   ${red}           .dF.      __      .88b   d88P       __     "
echo -e "   ${red}          .dF.     d888888b    .88b          d888888b "
echo -e "   ${red}        .dF.      d8b  .Y88b    .88b.       d8b  .Y88b"
echo -e "   ${cyn}      .dF.        888b(*)888xxxxxx888bxxxxxx888b(*)888"
echo -e "   ${cyn}    .dF.           .888oo8P         .88b     .888oo8P "
echo -e "   ${cyn}  .dF.               ~~~~     d88P   .88b       ~~~   "
echo -e "   ${cyn}.dF.                          .88b.   888|            "
echo -e "   ${cyn}88b.                            .88b.d88P             "
echo -e "   ${cyn}.888b.                            ~~~~~               "
echo -e "   ${grn}   .888b.           .d8888b.      d888888888==-       "
echo -e "   ${grn}      .888b.        8888L 88b.    .888888P~~          "
echo -e "   ${grn}         .888b.      .8F  8888xxxxx8888xxxxxxxxxxx88  "
echo -e "   ${grn}            .888b.        d8P.....................~~  "
echo -e "   ${grn}               .888b.. ..d8F                          "
echo -e "   ${grn}                  .888888F                            "
echo -e "   ${grn}                     ~~~                              "
echo                                                                    
echo -e "  ${cyn}    distro ${rst}"  " $distro" " ${cyn} kernel ${rst}"  " $kernel "                         
echo -e "  ${grn}    wm     ${rst}"  " $wm   " " ${grn}      pkgs    ${rst}"  "$pkgs   "                          
echo -e "  ${red}    shell  ${rst}"  " $she    " " ${red}   up    ${rst}"  "  $up   "                        
echo -e "  ${prp}    editor ${rst}"  " $EDITOR   " " ${prp}     date    ${rst}"  "$dt   "                         
echo                                                                    
echo
